before:
  hooks:
    - go mod download

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

builds:
  - binary: bionic
    env:
      - CGO_ENABLED=1

brews:
  - tap:
      owner: bionic-dev
      name: homebrew-bionic
      token: "{{ .Env.API_GITHUB_TOKEN }}"
    folder: Formula
    homepage: https://github.com/bionic-dev/bionic
