before:
  hooks:
    - go mod download

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

builds:
  - binary: bionic

brews:
  - tap:
      owner: shekhirin
      name: homebrew-bionic-cli
    folder: Formula
    homepage: https://github.com/shekhirin/bionic-cli
